spring: 
  application:
    name: matrix-front-content
  datasource:
    url: jdbc:mysql://120.78.208.3:3306/matrix
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: jasonFX3A87WLQ

mybatis:
  mapper-locations: classpath:com.matrix.mapper/*Mapper.xml
  type-aliases-package: com.matrix.pojo

server:
  port: 10051
