spring:
  application:
    name: matrix-config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/MentalKali/MatrixBlog
          search-paths: /**
          username: GitHub UserName
          password: GitHub PassWord

eureka:
  client:
    service-url:
      defaultZone: http://jason-dell:10010/eureka/,http://jason-dell:10011/eureka/

server:
  port: 10022
